<div class="item-showcase row">
<?php foreach ($attachments as $attachment): ?>
    <div class="col-md-4 item resource">
    <?php
    $item = $attachment->item();
    if ($item):
    ?>
        <?php
        $media = $attachment->media() ?: $item->primaryMedia();
        if ($media):
            echo $item->linkRaw($this->thumbnail($media, $this->thumbnailType));
        endif;
        ?>
        <?php $showTitleOption = $this->showTitleOption; ?>
        <?php if ($showTitleOption == 'item_title'): ?>
        <div class="title"><?php echo $item->link($item->displayTitle()); ?></div>
        <?php elseif ($showTitleOption == 'file_name'): ?>
        <div class="title"><?php echo $media->displayTitle(); ?></div>
        <?php endif; ?>
    <?php endif; ?>

    <?php
    $caption = $attachment->caption();
    if ($caption):
    ?>
        <div class="caption"><?php echo $caption; ?></div>
    <?php endif; ?>
    </div>
<?php endforeach; ?>
</div>
