<?php
/*
 * Copyright BibLibre, 2016
 * Copyright Daniel Berthereau, 2018
 *
 * This software is governed by the CeCILL license under French law and abiding
 * by the rules of distribution of free software.  You can use, modify and/ or
 * redistribute the software under the terms of the CeCILL license as circulated
 * by CEA, CNRS and INRIA at the following URL "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability.
 *
 * In this respect, the user's attention is drawn to the risks associated with
 * loading, using, modifying and/or developing or reproducing the software by
 * the user in light of its specific status of free software, that may mean that
 * it is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 */

/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Basket\Api\Representation\BasketItemRepresentation[] $basketItems
 */

$translate = $this->plugin('translate');
?>
<?php $this->pageTitle($translate('Basket')); ?>

<div class="basket-header">
    <h2>Panier</h2>

    <div class="basket-sort">
        <span><?php echo $translate('Sort mode:'); ?></span>
        <?php echo $this->partial('psl/basket-sort-field', [
            'title' => 'Titre',
            'sort_by' => 'dcterms:title',
        ]); ?>
        <?php echo $this->partial('psl/basket-sort-field', [
            'title' => 'Auteur',
            'sort_by' => 'dcterms:creator',
        ]); ?>
        <?php echo $this->partial('psl/basket-sort-field', [
            'title' => 'Date',
            'sort_by' => 'dcterms:date',
        ]); ?>
    </div>

    <div class="basket-display-options">
        <a id="basket-view-type-grid" href="#"><img src="<?php echo $this->assetUrl('img/grid.svg'); ?>"/></a>
        <a id="basket-view-type-list" href="#"><img src="<?php echo $this->assetUrl('img/list.svg'); ?>"/></a>
    </div>
</div>

<?php
    $resources = [];
    foreach ($basketItems as $basketItem) {
        $resource = $basketItem->resource();
        $resources[$resource->resourceName()][] = $resource;
    }

    $items = isset($resources['items']) ? $resources['items'] : [];
    $media = isset($resources['media']) ? $resources['media'] : [];
?>

<?php if (!empty($items)): ?>
    <h3><?php echo count($items) == 1 ? $translate('1 item') : sprintf($translate('%s items'), count($items)); ?></h3>
    <div class="resource-list">
        <?php foreach ($items as $item): ?>
            <?php echo $this->partial('search/resource', ['resource' => $item]); ?>
        <?php endforeach; ?>
    </div>
<?php endif; ?>

<?php if (!empty($media)): ?>
    <h3><?php echo count($media) == 1 ? $translate('1 file') : sprintf($translate('%s fichiers'), count($media)); ?></h3>
    <div class="resource-list">
        <?php foreach ($media as $medium): ?>
            <?php echo $this->partial('search/resource', ['resource' => $medium]); ?>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
