<?php
/*
 * Copyright BibLibre, 2016
 * Copyright Daniel Berthereau, 2017-2018
 *
 * This software is governed by the CeCILL license under French law and abiding
 * by the rules of distribution of free software.  You can use, modify and/ or
 * redistribute the software under the terms of the CeCILL license as circulated
 * by CEA, CNRS and INRIA at the following URL "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability.
 *
 * In this respect, the user's attention is drawn to the risks associated with
 * loading, using, modifying and/or developing or reproducing the software by
 * the user in light of its specific status of free software, that may mean that
 * it is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 */

/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Search\Api\Representation\SearchPageRepresentation $searchPage
 * @var \Search\Query $query
 * @var \Search\Response $response
 * @var array $sortOptions
 * For block layout:
 * @var string $heading Unused in current template.
 * @var bool $skipFormAction Remove action of the form, so it uses current page.
 */

$translate = $this->plugin('translate');

$isPartial = !$site;
$skipFormAction = !empty($skipFormAction);

$this->htmlElement('body')->appendAttribute('class', 'search');
$this->headLink()->appendStylesheet($this->assetUrl('css/search.css', 'Search'));
$this->headScript()->appendFile($this->assetUrl('js/search.js', 'Search'), 'text/javascript', ['defer' => 'defer']);
$this->headTitle($translate('Search'), \Zend\View\Helper\Placeholder\Container\AbstractContainer::PREPEND);
//$query['per_page'] => 20;
?>

<?php if (empty($isPartial)): ?>
<div id="content" role="main">
<?php endif; ?>

<?php if (isset($response)): ?>
    <div class="search-results-wrapper">
        <?= $this->partial('search/facets', ['searchPage' => $searchPage, 'query' => $query, 'response' => $response]) ?>
        <div class="search-results">
            <?php if ($response->getTotalResults() > 0): ?>
                <?= $this->partial('search/results-header', [
                    'query' => $query,
                    'response' => $response,
                    'sortOptions' => $sortOptions,
                ]) ?>

                <?php $itemSetsCount = $response->getResourceTotalResults('item_sets'); ?>
                <?= $this->partial('search/resource-list', [
                    'site' => $site,
                    'title' => sprintf($this->translatePlural('%s item set', '%s item sets', $itemSetsCount), $itemSetsCount),
                    'response' => $response,
                    'resourceName' => 'item_sets',
                ]) ?>

                <?php $itemsCount = $response->getResourceTotalResults('items'); ?>
                <?= $this->partial('search/resource-list', [
                    'site' => $site,
                    'title' => sprintf($this->translatePlural('%s item', '%s items', $itemsCount), $itemsCount),
                    'response' => $response,
                    'resourceName' => 'items',
                ]) ?>
                
                <?= $this->partial('search/results-footer', [
                    'query' => $query,
                    'response' => $response,
                    'sortOptions' => $sortOptions,
                ]) ?>

            
            <?php elseif (empty($query)): ?>

                <div class="noresults"><?= $translate('Fill a query and get results.') ?></div>

            <?php else: ?>

                <div class="noresults"><?php echo $translate('Your query returned no results'); ?></div>

            <?php endif; ?>
        </div>

    </div>
<?php endif; ?>
<?php if (empty($isPartial)): ?>
</div>
<?php endif; ?>