<?php
/*
 * Copyright BibLibre, 2016
 * Copyright Daniel Berthereau, 2018
 *
 * This software is governed by the CeCILL license under French law and abiding
 * by the rules of distribution of free software.  You can use, modify and/ or
 * redistribute the software under the terms of the CeCILL license as circulated
 * by CEA, CNRS and INRIA at the following URL "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability.
 *
 * In this respect, the user's attention is drawn to the risks associated with
 * loading, using, modifying and/or developing or reproducing the software by
 * the user in light of its specific status of free software, that may mean that
 * it is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 */

/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Search\Response $response
 * @var string $resourceName
 * @var string $title
 */

$results = $response->getResults($resourceName);
?>

<?php if (count($results)):
    $headingTerm = $this->siteSetting('browse_heading_property_term', 'dcterms:title');
    $bodyTerm = $this->siteSetting('browse_body_property_term', 'dcterms:description');
    $bodyTerms = $this->themeSetting('browse_body_property_terms', [$bodyTerm]);

    $itemSets = $this->params()->fromQuery('itemSet');
    if (!empty($itemSets['ids'][0]) && count($itemSets['ids']) == 1):
        $itemSet = $this->api()->read('item_sets', $itemSets['ids'][0])->getContent();
        $title = $itemSet->displayTitle() . ' : ' . $title;
    endif;
?>
<div class="resource-list">
    <?php
    foreach ($results as $result):
        $resource = $this->api()->read($resourceName, $result['id'])->getContent();
        echo $this->partial('search/resource', [
            'resource' => $resource,
            'headingTerm' => $headingTerm,
            'bodyTerms' => $bodyTerms,
            'tag' => 'div',
        ]);
    endforeach;
    ?>
</div>
<?php endif; ?>